language: go

go:
  - 1.x

sudo: false

env:
  global:
  - NODE_VERSION=latest

install:
  - go get -t -v ./...

before_deploy:
  - npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy --dir=tmpl --prod
  skip_cleanup: true
  on:
    branch: master
